"""canonical source path identity, processing version, chunk provenance

Revision ID: 70674399f988
Revises: 38b881eb3602
Create Date: 2026-08-22 18:11:43.654675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70674399f988'
down_revision: Union[str, Sequence[str], None] = '38b881eb3602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('section_index', sa.Integer(), nullable=False))
    op.add_column('chunks', sa.Column('section_chunk_index', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_chunk_provenance', 'chunks', ['document_id', 'section_index', 'section_chunk_index'])
    op.drop_column('chunks', 'chunk_index')
    op.add_column('documents', sa.Column('source_path', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('source_content_hash', sa.String(length=64), nullable=False))
    op.add_column('documents', sa.Column('processing_version', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('embedding_model_name', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_documents_source_path'), 'documents', ['source_path'], unique=True)
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'filepath')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filepath', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_documents_source_path'), table_name='documents')
    op.drop_column('documents', 'embedding_model_name')
    op.drop_column('documents', 'processing_version')
    op.drop_column('documents', 'source_content_hash')
    op.drop_column('documents', 'source_path')
    op.add_column('chunks', sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_chunk_provenance', 'chunks', type_='unique')
    op.drop_column('chunks', 'section_chunk_index')
    op.drop_column('chunks', 'section_index')
    # ### end Alembic commands ###
